### PR TITLE
Release v0.9.0-rc.1

### PR DESCRIPTION
**Pull request by kamilkisiela**
@Urigo I think we should publish it first as a Release Candidate because of this UMD thing and updated AoT compilation

- [x] #195
- [ ] #206
- [ ] apollostack/angular2-docs#23

### CODE REVIEW

**Comment by intellix** [comment]
Just wanna add that 2.3.1 was just released and apparently has a few AOT things there: https://github.com/angular/angular/blob/master/CHANGELOG.md#note

**Comment by armstrjare** [comment]
Are we able to get this on npm, even if it's with a RC tag? Currently dealing with upgrading to ng 2.3+ and is this causing issues. Big pain to work around since the OpaqueToken for AngularApolloClient isn't exported by the module...

**Comment by kamilkisiela** [comment]
@armstrjare I will do my best to publish it soon! I `Promise`.

**Comment by Urigo** [comment]
I wanted turtila wait for Apollo Client 0.6, mostly for some improvements we've done in bundling, but I've just talked with Kamil and we'll release something later today (when I'll be in front of the computer) and then another RC once Apollo Client will be released as well

**Comment by kamilkisiela** [comment]
@Urigo okay, it's ready

**Comment by Urigo** [comment]
publish `0.9.0-rc.1`
thanks @kamilkisiela

**Pull request merged**
