### PR TITLE
Refetch, polling, loading, basically all

### PR DESCRIPTION
**Pull request by kamilkisiela**
An example of usage:

```js
this.exampleMutation(options)
  .then((graphQLResult) => {
    this.exampleQuery.refetch();
  });
```

**UPDATE** - see [that comment](https://github.com/apollostack/angular2-apollo/pull/19#issuecomment-226164012)

---

**Outdated now**
```html
<li *ngFor="let example of exampleQuery | apolloQuery:'examples'">
  {{ example.description }}
</li>
```

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@jboothe So here's an idea you're interested in :)

**Comment by kamilkisiela** [comment]
While I was working on [GitHunt for Angular2](http://github.com/kamilkisiela/GitHunt-angular2) I added few new features. 

@stubailo You might be interested in the progress :rocket: 

@Urigo There are still no tests for that features so for now it's just a sort of concept rather then "ready to go" thing.

### So what's new?

- `Apollo` decorator is now able to handle or to be more precise, gives an access to **few queries** inside a one root query.
- options of mapped queries are now the same as in ApolloClient's `watchQuery` method (`forceFetch`, `returnPartialData` and `pollInterval`)
- `refetch()` is now supported
- `unsubscribe()` is also available
- `stopPolling()` is done
- `startPolling()` too
- `loading` - boolean property with loading status

Result of a query:

```js
{
  loading: boolean
  errors: any[]
  refetch: Function
  unsubscribe: Function
  stopPolling: Function
  startPolling: Function
  ...
  [string]: any // query name as a key and result of that query as value 
  // (an example: `feed`: [{id: 1}, {id: 3}, {id: 5}])
}
```

---

### An example:

```ts
@Component({
  selector: 'app',
  templateUrl: '/app.html'
})
@Apollo({
  client,
  queries(context) {
    return {
      data:  {
        query: gql`
          query Feed($type: FeedType!) {
            currentUser {
              login
            }
            feed(type: $type) {
              createdAt
              id
            }
          }
        `,
        variables: {
          type: context.type ? context.type.toUpperCase() : 'TOP'
        },
        forceFetch: true,
      }
    };
  }
})
class App {}
```

```html
<loading *ngIf="data.loading"></loading>
<feed-entry
  *ngIf="!data.loading" 
  *ngFor="let entry of data.feed" 
  [entry]="entry"
  [currentUser]="data.currentUser"
  (onVote)="onVote($event)">
</feed-entry>
```

**Comment by kamilkisiela** [comment]
And a working implementation of it (one issue with additional record in ngFor, but that's all) https://github.com/kamilkisiela/GitHunt-angular2/commit/a0593e4afb8c8bb402cb0f04ab26b4437b3a1017

**Comment by kamilkisiela** [comment]
After releasing this, [GitHunt for Angular2](http://github.com/kamilkisiela/GitHunt-angular2) will be practically ready.

**Comment by helfer** [comment]
Thanks a lot! @kamilkisiela

**Comment by kamilkisiela** [comment]
@helfer It's always a pleasure to help!

**Pull request merged**
