### PR TITLE
chore: commit message checking

### PR DESCRIPTION
**Pull request by kamilkisiela**
Same thing as in `angular-meteor` which is a commit message validation using angular.js guidelines.

### CODE REVIEW

**Comment by Urigo** [comment]
yes I really believe in that convention, it helps me a lot on `angular-meteor`.
@stubailo what do you think about using the same conventions on all of Apollo's repos?

**Comment by stubailo** [comment]
I don't want to use it on all other repos yet, let's see how it goes on this one.

Personally I really hate referring to anything I do as a "chore".

**Comment by Urigo** [comment]
haha, ok , we'll use it only here for now.
Also I guess Angular developers are more use to it because it came from the Angular repo

**Comment by kamilkisiela** [comment]
Yeah ;) It's in use in many ng repos

**Pull request merged**
